global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['192.168.0.114:8082']
        labels:
          env: 'local'

  - job_name: 'traefik-nomad'
    static_configs:
      - targets: ['192.168.0.114:9092']
        labels:
          env: 'local'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.114:7100']
        labels:
          env: 'local'

