global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nomad"
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['localhost:4646']
        labels:
          env: 'local'

  - job_name: 'traefik'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          env: 'local'

