services:
  prometheus:
    image: prom/prometheus:latest
    container_name: benchmark-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - "9091:9090"
    extra_hosts:
      - "192.168.0.114:host-gateway"
    deploy:
      resources:
        limits:
          memory: 6G

  grafana:
    image: grafana/grafana:latest
    container_name: benchmark-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          memory: 6G

  k6:
    image: grafana/k6:latest
    container_name: benchmark-k6
    volumes:
      - ./k6/scripts:/scripts
      - ./k6/reports:/reports
    working_dir: /scripts
    environment:
      - TARGETS=192.168.0.114:3005,192.168.0.114:3006,192.168.0.114:3007,192.168.0.114:3008,192.168.0.114:3009,192.168.0.114:3011,192.168.0.114:3014,192.168.0.114:3016
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(95),p(99),avg

    extra_hosts:
      - "192.168.0.114:host-gateway"
    command: [ "run", "-o", "experimental-prometheus-rw", "load-all.js" ]
    profiles:
      - tools
  # - TARGETS=192.168.0.114:3005,192.168.0.114:3006,192.168.0.114:3007,192.168.0.114:3008,192.168.0.114:3009,192.168.0.114:3011,192.168.0.114:3014,192.168.0.114:3016
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: benchmark-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@192.168.0.114:5432/benchmark?sslmode=disable
    extra_hosts:
      - "192.168.0.114:host-gateway"
    ports:
      - "9187:9187"
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  prometheus_data:
